#168: Add possibility to set 2 ISO values: preview and capture
pibooth/pibooth pull request #232
Opened 2021-04-29 16:19 UTC by anxuae

2021-04-29 16:23 UTC, anxuae commented
Shall we keep the `gphoto_omx.py` implementation? I try to update it when something change in the cameras classes, but it is hard to say if it is correct at this class has never been finished.

2021-04-29 18:43 UTC, werdeil reviewed
I think we shall be explicit in the code names: iso_preview and iso_capture
And reserve iso for the config / tuple

2021-04-29 18:45 UTC, werdeil commented
> Shall we keep the `gphoto_omx.py` implementation? I try to update it when something change in the cameras classes, but it is hard to say if it is correct at this class has never been finished.

I think we can drop it. It was only an exploration

2021-05-02 21:20 UTC, werdeil requested changes
two small comments

2021-05-02 21:20 UTC, werdeil commented on pibooth/camera/opencv.py
> +            print(self.iso_preview)
I think you left a debug print here

2021-05-02 21:20 UTC, werdeil commented on pibooth/camera/base.py
> +        self.iso_capture = iso[1]
Up to you but we can change it to:
```suggestion
        self.iso_preview, self.iso_capture = iso
```

2021-05-03 18:56 UTC, anxuae commented on pibooth/camera/opencv.py
> +            print(self.iso_preview)
Corrected

2021-05-03 18:58 UTC, merged